### ISSUE TITLE
Investigate Public API options

### ISSUE THREAD

**Issue by markolson** [markolson/kickscraper#16]
Given the new disclaimer on the private API, which looks like it may cause kick scraper user's accounts to be in jeopardy, we need to rework things until the proper API is re-opened, if it ever is. By "Public API", I mean requests that the website itself makes for data to some endpoint that may be authenticated by a cookie, but not an oauth token. We should be able to use something like Mechanize to do this.

### User
- [ ] By ID

### Project
- [ ] By ID
- [ ] By Slug

### Project list
- [x] Backed By User
- [x] Recently Launched
- [x] Ending Soon
- [ ] Nearby
- [x] Popular
- [x] Most Funded
- [x] By Category
- [x] Staff Picks
- [x] Advanced Search
- [ ] Successful (if possible!)

### Categories
- [ ] By ID

### Notifications 
- [ ] By Project
- [ ] By User
- [ ] By ID

### Updates
- [ ] By Project
- [ ] By User
- [ ] By ID

### Comments
- [ ] By Project
- [ ] By User
- [ ] By ID

Add a comment with what you found, how you got to it, and a link to a wiki page with sample output.

**Comment by rwcatalano** [comment]
Hi there, as of Saturday I've been getting a 503 response from every automated request to kickstarter.com.  It works on my local dev box, but fails on 2 different servers on 2 different hosts.  Any ideas?  Works in the web browser and in postman too.

**Comment by benrugg** [comment]
Hey @rwcatalano - I'm not sure what would cause this. Definitely strange that it works for you on your local machine, but not in production. Maybe you've got the debugging proxy enabled? Check the rails environment you're running on those severs. (or see app/models/kickstarter.rb).

**Comment by ronenteva** [comment]
Any updates about searching for a project by ID?

**Comment by benrugg** [comment]
@ronenteva, at this point, I don't think anyone is actively working on adding new features like this. Kickstarter's API is still difficult to use, and occasionally changing without notice. I'm still hoping they make a public one someday!

**Comment by global-pih** [comment]
Hello
How are you?
My name is jack.
I am going to get backer count and pledged project url in kickstarter.
How can i get it?
Please help me.My email is jack.telman12345@gmail.com
My skype is "Global Talent Manager" for red rose.
Thanks

**Comment by mankinchi** [comment]
2020 is here now and still nothing like that :)). Some of the end points are still working fine but no public confirmation whatsoever :))

**Comment by benrugg** [comment]
Ha, yeah, Kickstarter went from world-changing phenomenon to meh 🤷‍♂️

**Comment by jdieguez89** [comment]
Hi guys, I started a project to download data from Kickstarter, such as media(including images and videos), project info, and author info. This software is in beta, but you can try it. I hope that resolves your problems. Soon has finished the documentation I will share you; if you are interested in this project, write to me, Regards

**Comment by benrugg** [comment]
Hey @jdieguezbean - thanks for posting this. For me personally, I'm not gathering data from Kickstarter anymore, but I'm glad someone is still thinking about it. Good luck on your project!

**Comment by ObaydaAlesawi** [comment]
@jdieguezbean @benrugg 
I always this Captcha issue when I'm trying to fetch the data 
![image](https://user-images.githubusercontent.com/32073999/109332721-90255200-786f-11eb-8b29-cf0148d5b5ed.png)
Do you know how can I ignore or do anything about this issue?

**Comment by benrugg** [comment]
@Algeneralo ah, that's interesting. It must've been added since the last time I used kickscraper. I stopped using it about a year ago - sorry that I can't help with this!

**Comment by FSou1** [comment]
You can use `per_page` parameter to set a number of projects to return (1 to 48)
