### ISSUE TITLE
Pulling the company website for each project

### ISSUE THREAD

**Issue by eddeo93** [markolson/kickscraper#25]
Thank you so much for this very useful kickscraper tool. I was wondering if there was a way we could pull out the actual company website as well as the email address of the creator? 

Not the project url, as we could already get the urls. I would like to see if we can obtain the actual company website url. 

Thanks.

**Comment by benrugg** [comment]
Hey @eddeo93 - that's a great question... I actually thought this was possible, but I just messed around with it for a bit and I guess it's not...

You can get close by finding a user (or finding a project and then doing `user = c.find_user project.creator.id`), which gives their bio, etc. But apparently kickstarter's api doesn't return their website(s).

**Comment by eddeo93** [comment]
I see... Thanks!
