### ISSUE TITLE
Kickstart login failing?

### ISSUE THREAD

**Issue by benrugg** [markolson/kickscraper#28]
Hey @markolson @jamlen @NolaMark @ajkerrigan @danleveille - 

Do any of you guys have an active project that is using kickscraper right now? My project (Jumpkick) started having login failures yesterday morning and I can't seem to get any info from Kickstarter's API anymore.

I was wondering if anyone else is having the same problem...

**Comment by NolaMark** [comment]
Haven't used in quite some time.  Sorry no helpful datapoint to add.

**Comment by ajkerrigan** [comment]
I don't, no. I actually killed my project and removed it from GitHub because I felt like the kind of data-grabbing I wanted to do was violating the spirit (if not the letter) of Kickstarter's API policies. I hope this is a short-lived issue for your sake though.

**Comment by markolson** [comment]
Sorry man, I haven't run this in a while either. I can fire up Charles tomorrow and see what's up if it continues through tomorrow.

**Comment by benrugg** [comment]
Thanks for getting back to me so quickly, guys. I'm in touch with Kickstarter support, so hopefully I'll figure out something soon :-)

**Comment by benrugg** [comment]
Got it working, guys! It looks like Kickstarter's API now requires content-type: application/json to be set in request headers. Great that it was a quick fix.
