### ISSUE TITLE
how to use find_project to find a specify project?

### ISSUE THREAD

**Issue by hothero** [markolson/kickscraper#34]
I didn't get project by id or slug, anyone can successfully use this feature?

``` ruby
client = Kickscraper.client
p = client.search_projects("aqua").first
client.find_project(p.slug) # return nil
client.find_project(p.id) # also return nil
```

**Comment by benrugg** [comment]
Hey @hothero - I just checked this out. This definitely used to work and now it doesn't.

I also just looked through some of the project data I have, and it looks like this broke on Nov 10th. 

I will see if there is an alternative way to query Kickstarter to make this work again...

**Comment by hothero** [comment]
Thanks for your help. Or you have any source about Kickstarter API Usage? I think I can help to fix it, but I don't have document.

**Comment by benrugg** [comment]
You know what... there isn't any kind of public API documentation. If you look through some of the issues on this repo, though, you'll see where we have done a bit of our own documenting.

Definitely feel free to contribute and make a pull request!

**Comment by benrugg** [comment]
@hothero - another contributor just fixed this issue. If you're still trying to use kickscraper, grab this latest version and you should be good to go. I'll post this update to rubygems asap...
