### ISSUE TITLE
Finding website of users?

### ISSUE THREAD

**Issue by Bugsbane** [markolson/kickscraper#36]
I'm just trying to see if there's any way to get the websites of a small list of users, ie for the new and noteworthy projects in a specific category.

Seems that it's possible to get the list of projects, and then from that the list of founder creators, however it wasn't clear how to list their websites where available.

I see there's a category for URL's per user, but these seem to be Kickstarter URL's.

Has a field been found for users public info such as their own website?

**Comment by benrugg** [comment]
I tried this at one point, too. I wish it was possible, but I don't think it is. I'm still not sure why Kickstarter hasn't opened up their entire API publicly to spur on community involvement!
