### ISSUE TITLE
Rate Limits?

### ISSUE THREAD

**Issue by mgreenberg** [markolson/kickscraper#37]
Anyone have any idea on the rate limits that Kickstarter imposes on API / scraping clients? Would really like to play within the rules and not get blacklisted.. Thanks!

**Comment by benrugg** [comment]
When I was first building my app, I hit a limit of 600 API calls / hour. I'm not sure if that's still the limit, but that's what it was a couple years ago.

**Comment by mgreenberg** [comment]
Thanks!
