### ISSUE TITLE
how to scrape data about the project creators?

### ISSUE THREAD

**Issue by hannahwen** [markolson/kickscraper#45]
Hi everyone, I am doing academic research about project description and crowdfunding success. i have a dataset of 2000+ projects, and I would like to also get information about their creators (as mentioned in the WIKI), such as the biography of the creators and whether they have posted their facebook accounts, and if yes, how many friends they have. What can I do to scrape those data? Many thanks!!!

**Comment by benrugg** [comment]
I think you can get a little bit of info about project creators through Kickstarter's API... unfortunately it won't be nearly as much as you're looking for, I think. Here's the general idea of what you can do:

```
c = Kickscraper.client
project = c.search_projects('whatever').first # or project = c.find_project xxxxxxxxx (kickstarter id number)
puts project.creator.inspect
```
