### ISSUE TITLE
in `parse': 765: unexpected token 

### ISSUE THREAD

**Issue by mial-radja** [markolson/kickscraper#46]
Hi,
when I try to scrap projects I have this error
C:/Ruby25-x64/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" (Faraday::Error::ParsingError)
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name='viewport' content='width=device-width, initial-scale=1.0' />
  <link href="https://d3mlfyygrfdi2i.cloudfront.net/favicon.png?v=2" rel="icon" type="image/png">
  <title>We're sorry, but something went wrong (500)</title>
  <style type="text/css">
    body {
      background-color:#fff;
      color: #282828;
      font-family: "Maison Neue Book","Helvetica Neue", arial, sans-serif;
    }
    .message {border: 1px solid #656969; padding: 24px;}
    .message p:last-child {margin-bottom: 0;}

    .tciquote {
      padding: 30px 0;
      display: block;
      color: #9B9E9E;
      line-height: 1.2;
    }
    .tcilogo {width: 60px; height: auto; float: none; margin-left: auto; margin-right: auto; margin-top: 6px; margin-bottom: 18px; display: block; text-align: center;}
    .tciquote p {font-family: "Cooper Light", serif; font-size: 15px;}
    .tciquote footer {text-transform: uppercase; font-size: 12px; color: #9B9E9E;}
    .tciquote a, .tciquote a:hover {text-decoration: none;}
    .tciquote .readmore {font-size: 12px; text-transform: uppercase; margin-top: 12px;}
    .tciquote a:hover .readmore {text-decoration: underline}

    h1 { font-size: 400%; line-height: 1em; margin: 0; padding: 0; font-weight: 400; margin-bottom: 0.1em;}
    p { color: #282828; line-height: 1.5; font-size: 90%; margin-bottom: 18px; margin-top: 0;}
    a { color: #282828; }
    a:hover { color: #037362 }
    .logo { display: block; margin-left: auto; margin-right: auto; border: 0; text-align: center; margin-bottom: 36px; max-width: 190px; height: auto;}
    body { padding: 20px; }
    @media screen and (min-width: 550px) {
      .logo {
        margin-bottom: 42px;
        margin-left: 0;
        margin-right: 0;
      }
      body {
        width: 530px;
        margin: 65px auto 0 auto;
      }
      .message {padding: 36px;}
      p {font-size: 95%;}
      .tciquote {padding: 24px 0;}
      .tcilogo {width: 60px; display: inline-block; float: left; margin-bottom: 120px; margin-right: 24px; margin-top: 18px;}
      .tciquote p {display: block; text-align: left; margin-top: 18px;}
    }
...
at first, it was working well for some time then It stops,  but now I have this error from the beginning.

**Comment by benrugg** [comment]
That error happens when kickscraper tries to parse the api response that it expects to be JSON, but it's actually an HTML error page returned by Kickstarter.

I just tested everything on my end, and for sure it's all still working (with a user/pass and without it). I would guess that somehow you're doing a query on the API that has invalid data in it... or maybe in an invalid format?
