### ISSUE TITLE
Captcha Issue

### ISSUE THREAD

**Issue by ObaydaAlesawi** [markolson/kickscraper#48]
I always this Captcha issue when I'm trying to fetch the data 
![image](https://user-images.githubusercontent.com/32073999/109332721-90255200-786f-11eb-8b29-cf0148d5b5ed.png)
anyone know how can I ignore or do anything about this issue?

**Comment by benrugg** [comment]
@Algeneralo ah, that's interesting. It must've been added since the last time I used kickscraper. I stopped using it about a year ago - sorry that I can't help with this!
